name: Deploy to Elastic Beanstalk

on:
  push:
    tags:
      - 'v*'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: sbh
  EB_APPLICATION_NAME: sbh
  EB_ENVIRONMENT_NAME: sbh-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        docker build --build-arg APP_VERSION=${{ github.ref_name }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker build --build-arg APP_VERSION=${{ github.ref_name }} -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
    - name: Generate deployment packages
      run: |
        # Create deployment package for web environment
        zip -r deploy.zip . -x "*.git*" "node_modules/*" "tests/*" "*.pyc" "__pycache__/*" "instance/*" "*.log"
        
        # Create deployment package for worker environment
        zip -r deploy-worker.zip . -x "*.git*" "node_modules/*" "tests/*" "*.pyc" "__pycache__/*" "instance/*" "*.log"
        
    - name: Deploy to Elastic Beanstalk (Web)
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
        version_label: ${{ github.ref_name }}
        region: ${{ env.AWS_REGION }}
        deployment_package: deploy.zip
        wait_for_deployment: true
    
    - name: Deploy to Elastic Beanstalk (Worker)
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        environment_name: sbh-worker
        version_label: ${{ github.ref_name }}
        region: ${{ env.AWS_REGION }}
        deployment_package: deploy-worker.zip
        wait_for_deployment: true
        
    - name: Wait for deployment to stabilize
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 180
        
    - name: Run smoke tests
      run: |
        # Run smoke tests against the deployed environment
        python scripts/smoke_prod.py
      env:
        PUBLIC_BASE_URL: ${{ secrets.PUBLIC_BASE_URL }}
